### ISSUE TITLE
Pick the technological stack

### ISSUE THREAD

**Issue by FilipKolodziejczyk** [FilipKolodziejczyk/software-engineering-2#2]
Let's list the technologies we know and then decide what to pick.

**Comment by FilipKolodziejczyk** [comment]
Frontend: barely React + Typescript
Backend: a bit Python (no framework at all), Spring Boot (Java + Maven), a bit ASP .NET CORE

**Comment by adam-kwiatkowski** [comment]
Frontend: Vue.js, some React
Backend: Laravel, FastAPI, ASP.NET
DB: MSSQL, MySQL

**Comment by zalewskij** [comment]
Frontend: Dash (python library based on React)
Backend: Django (but just a little)
DB: PostgreSQL, MySQL, MSSQL

**Comment by blazej-misiura** [comment]
Frontend: React
Backend: -
DB: MySQL, MSSQL

**Comment by siekaczp** [comment]
Frontend: React (with typescript)
Backend: just a bit of node.js
DB: MySQL, MSSQL

**Comment by FilipKolodziejczyk** [comment]
According to the discussion, React was chosen for frontend, ASP.NET for backend and MSSQL as database (beneficial due to Linq).
