### ISSUE TITLE
Prepare Mockup UI

### ISSUE THREAD

**Issue by FilipKolodziejczyk** [FilipKolodziejczyk/software-engineering-2#5]
Create wireframes for customer, employee and delivery modules.

**Comment by adam-kwiatkowski** [comment]
https://www.figma.com/team_invite/redeem/gwSY9w6BjN5JxVcz73t12D

**Comment by blazej-misiura** [comment]
UI Mockup for employee and delivery. All the most important functionalities from the documentation have been included.

https://www.figma.com/file/dsFyDSfHkvLm02vURuBeYW/admin_delivery?t=rgBouvzIMLWRH2rD-1

**Comment by FilipKolodziejczyk** [comment]
@blazej-misiura in delivery module. Does it make sense to have a tab Orders since this is the only one tab there?

**Comment by FilipKolodziejczyk** [comment]
For me its just fine. But @adam-kwiatkowski , as a subject matter expert, please express your opinion.

**Comment by adam-kwiatkowski** [comment]
Looks good to me

**Comment by FilipKolodziejczyk** [comment]
@adam-kwiatkowski  if you will be done with your part, please update it here too so we can review and close issue as one

**Comment by adam-kwiatkowski** [comment]
Mobile version wireframes are mostly done and available [here](https://www.figma.com/file/GDBAnrSHF2CU4gGYCZ5xQ2/UI-Mockup?node-id=0%3A1&t=u2jfABBZ2UTay4PY-1). Desktop version won't differ much except for using the extra horizontal space, hence I'm not planning on making extra screens

**Comment by FilipKolodziejczyk** [comment]
Looks good. Let's keep it as it is and proceed to the implementation
