### ISSUE TITLE
Design the db schema

### ISSUE THREAD

**Issue by FilipKolodziejczyk** [FilipKolodziejczyk/software-engineering-2#6]
Some kind of graph required. It should cover the needed tables, fields in them along with types and relations.

**Comment by zalewskij** [comment]
Initial db schema:
[db_schema.pdf](https://github.com/FilipKolodziejczyk/software-engineering-2/files/10948557/db_schema.pdf)

**Comment by zalewskij** [comment]
@siekaczp or @FilipKolodziejczyk or @blazej-misiura or @adam-kwiatkowski 
I need a review whether 
[db_schema.pdf](https://github.com/FilipKolodziejczyk/software-engineering-2/files/10972586/db_schema.pdf)
is correct.

**Comment by adam-kwiatkowski** [comment]
Seems to me that employees and delivery staff should have logins and passwords, perhaps an additional `User` table would work? (I haven't looked into the relevant section of the system specification but [something like this](https://stackoverflow.com/a/43875759) looks reasonable). I would also like to suggest a name `OrderDetails` in place of `CurrentOrders` since that data is linked to orders regardless of their status. Everything else looks really good.

**Comment by FilipKolodziejczyk** [comment]
I think the same as Adam, we need credentials for all type of users. Nevertheless I would choose a TBC approach, that is separate tables per each class, since what Adam presented is inferior in terms of performance (some say that it is also good when security considered). I also have not studied the whole docs but I think Employees might be responsible for Complaints (I mean they should be related), right? Also usually Clients have Addresses. Product shouldn't have 1-to-1 relation with CurrentOrders (renaming to OrderDetails seems nice) but *-to-1. One product might be ordered multiple times (especially when I see inStock int property for product). The same with relation Order-DeliveryMan. One delivery man may have multiple packages at once right? And Client-Order. Same with Client-Complaint.

**Comment by zalewskij** [comment]
List of changes:
- added `username` and `password`  fields for all system users (TBC approach used)
- added address field to a `Client` 
- added `EmployeeID` to `Complaint` table to reflect the fact that concrete employee is responsible for a complaint
- fixed multiplicities in entities relationships

**Comment by FilipKolodziejczyk** [comment]
Could you post an updated version 😃 ?

**Comment by zalewskij** [comment]
An updated version of database schema is already on the wiki page of the project.

**Comment by FilipKolodziejczyk** [comment]
To my mind it is a sufficient design. All the minorities are expected to be resolved and adjusted during backend development process.
